// ============================================================
// MGN Networking System — Sample Healthcare Data
// modules/network/lib/network-data.ts
//
// TODO: Replace all exports here with real API calls
// when backend data is available.
// This file is intentionally isolated for easy replacement.
// ============================================================

import type { ProfessionalProfile, Community, NetworkPost } from "../types";

// ─────────────────────────────────────────────
// SAMPLE HEALTHCARE PROFESSIONALS
// Used in Discover tab when API returns empty or loading
// ─────────────────────────────────────────────

export const SAMPLE_PROFESSIONALS: ProfessionalProfile[] = [
  {
    id: "sample-1",
    user_id: "sample-1",
    name: "Dr. Rahul Sharma",
    email: "",
    profession: "Doctor",
    specialization: "Cardiology",
    primary_degree: "MBBS",
    additional_degrees: ["MD Cardiology"],
    designation: "Senior Cardiologist",
    organization: "AIIMS Raipur",
    city: "Raipur",
    state: "Chhattisgarh",
    country: "India",
    experience_years: 14,
    identity_verified: true,
    education_verified: true,
    registration_verified: true,
    experience_verified: false,
    connection_count: 1240,
    mutual_connections: 8,
    connection_status: "none",
    follow_status: "not_following",
    bio: "Interventional cardiologist with 14 years of experience in PCI, cardiac rehabilitation, and heart failure management.",
    skills: ["PCI", "Echocardiography", "Cardiac Cath", "Heart Failure Management"],
  },
  {
    id: "sample-2",
    user_id: "sample-2",
    name: "Dr. Priya Nair",
    email: "",
    profession: "Doctor",
    specialization: "Neurology",
    primary_degree: "MBBS",
    additional_degrees: ["DM Neurology"],
    designation: "Consultant Neurologist",
    organization: "KEM Hospital",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    experience_years: 10,
    identity_verified: true,
    education_verified: true,
    registration_verified: true,
    experience_verified: true,
    connection_count: 830,
    mutual_connections: 3,
    connection_status: "none",
    follow_status: "not_following",
    bio: "Specialist in stroke, epilepsy, and movement disorders. Passionate about clinical research and patient education.",
    skills: ["Stroke Management", "EEG", "Epilepsy", "Movement Disorders"],
  },
  {
    id: "sample-3",
    user_id: "sample-3",
    name: "Kavita Sharma",
    email: "",
    profession: "Physiotherapist",
    specialization: "Sports Rehabilitation",
    primary_degree: "BPT",
    additional_degrees: ["MPT (Sports)"],
    designation: "Senior Physiotherapist",
    organization: "Fortis Hospital",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    experience_years: 7,
    identity_verified: true,
    education_verified: true,
    registration_verified: false,
    experience_verified: false,
    connection_count: 560,
    mutual_connections: 12,
    connection_status: "none",
    follow_status: "not_following",
    bio: "Sports physiotherapist working with elite athletes. Special interest in ACL rehabilitation and return-to-sport protocols.",
    skills: ["ACL Rehab", "Manual Therapy", "Exercise Prescription", "Biomechanics"],
  },
  {
    id: "sample-4",
    user_id: "sample-4",
    name: "Dr. Amit Kumar",
    email: "",
    profession: "Doctor",
    specialization: "Orthopaedics",
    primary_degree: "MBBS",
    additional_degrees: ["MS Orthopaedics"],
    designation: "Orthopaedic Surgeon",
    organization: "Safdarjung Hospital",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    experience_years: 12,
    identity_verified: true,
    education_verified: true,
    registration_verified: true,
    experience_verified: true,
    connection_count: 970,
    mutual_connections: 5,
    connection_status: "none",
    follow_status: "not_following",
    bio: "Orthopaedic surgeon specializing in joint replacement and sports injuries. Over 2000 successful arthroplasty procedures.",
    skills: ["Knee Replacement", "Hip Arthroplasty", "Arthroscopy", "Sports Injuries"],
  },
  {
    id: "sample-5",
    user_id: "sample-5",
    name: "Dr. Anjali Gupta",
    email: "",
    profession: "Doctor",
    specialization: "Pediatrics",
    primary_degree: "MBBS",
    additional_degrees: ["MD Pediatrics"],
    designation: "Pediatric Consultant",
    organization: "SMS Hospital",
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    experience_years: 8,
    identity_verified: true,
    education_verified: true,
    registration_verified: true,
    experience_verified: false,
    connection_count: 420,
    mutual_connections: 2,
    connection_status: "none",
    follow_status: "not_following",
    bio: "Pediatrician with focus on newborn care, vaccination programs, and childhood nutrition.",
    skills: ["Neonatology", "Pediatric Nutrition", "Vaccination", "Child Development"],
  },
  {
    id: "sample-6",
    user_id: "sample-6",
    name: "Rajesh Menon",
    email: "",
    profession: "Pharmacist",
    specialization: "Clinical Pharmacy",
    primary_degree: "PharmD",
    additional_degrees: [],
    designation: "Clinical Pharmacist",
    organization: "Apollo Pharmacy",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    experience_years: 5,
    identity_verified: true,
    education_verified: true,
    registration_verified: false,
    experience_verified: false,
    connection_count: 310,
    mutual_connections: 1,
    connection_status: "none",
    follow_status: "not_following",
    bio: "Clinical pharmacist specializing in oncology pharmacy and medication therapy management.",
    skills: ["Oncology Pharmacy", "Drug Interactions", "Patient Counseling", "MTM"],
  },
  {
    id: "sample-7",
    user_id: "sample-7",
    name: "Dr. Suresh Reddy",
    email: "",
    profession: "Doctor",
    specialization: "Cardiology",
    primary_degree: "MBBS",
    additional_degrees: ["DM Cardiology", "FESC"],
    designation: "Head of Cardiology",
    organization: "Yashoda Hospitals",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    experience_years: 20,
    identity_verified: true,
    education_verified: true,
    registration_verified: true,
    experience_verified: true,
    connection_count: 2100,
    mutual_connections: 15,
    connection_status: "none",
    follow_status: "not_following",
    bio: "Senior interventional cardiologist and researcher. Author of 40+ peer-reviewed publications in cardiovascular medicine.",
    skills: ["Interventional Cardiology", "Research", "Medical Education", "TAVI"],
  },
  {
    id: "sample-8",
    user_id: "sample-8",
    name: "Meera Singh",
    email: "",
    profession: "Nurse",
    specialization: "Critical Care",
    primary_degree: "BSN",
    additional_degrees: ["MSN"],
    designation: "ICU Nurse Manager",
    organization: "Medanta Medicity",
    city: "Gurugram",
    state: "Haryana",
    country: "India",
    experience_years: 9,
    identity_verified: true,
    education_verified: true,
    registration_verified: true,
    experience_verified: false,
    connection_count: 680,
    mutual_connections: 7,
    connection_status: "none",
    follow_status: "not_following",
    bio: "Experienced ICU nurse manager passionate about evidence-based nursing and patient safety protocols.",
    skills: ["Critical Care", "Ventilator Management", "ACLS", "Patient Safety"],
  },
];

// ─────────────────────────────────────────────
// SAMPLE COMMUNITIES
// Used as fallback UI before API data loads
// ─────────────────────────────────────────────

export const SAMPLE_COMMUNITIES: Community[] = [
  {
    id: "c1",
    slug: "physiotherapy-india",
    name: "Physiotherapy India",
    description: "For physiotherapists, physical therapists, and rehab professionals across India.",
    specialty: "Physiotherapy",
    visibility: "public",
    join_mode: "open",
    member_count: 1240,
    post_count: 340,
    is_member: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c2",
    slug: "cardiology-network",
    name: "Cardiology Network",
    description: "Clinical cardiology discussions, research, and ECG interpretation.",
    specialty: "Cardiology",
    visibility: "public",
    join_mode: "open",
    member_count: 890,
    post_count: 210,
    is_member: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c3",
    slug: "medical-students-forum",
    name: "Medical Students Forum",
    description: "For MBBS, BDS, BPT, BSN and allied health students across India.",
    specialty: "Medical Students",
    visibility: "public",
    join_mode: "open",
    member_count: 3400,
    post_count: 890,
    is_member: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c4",
    slug: "clinical-research-hub",
    name: "Clinical Research Hub",
    description: "Multi-center trial collaboration, research methodology, and publication support.",
    specialty: "Clinical Research",
    visibility: "public",
    join_mode: "open",
    member_count: 560,
    post_count: 130,
    is_member: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c5",
    slug: "nursing-excellence",
    name: "Nursing Excellence",
    description: "For nurses, nurse practitioners, and nursing educators.",
    specialty: "Nursing",
    visibility: "public",
    join_mode: "open",
    member_count: 2100,
    post_count: 560,
    is_member: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c6",
    slug: "sports-medicine-rehab",
    name: "Sports Medicine & Rehab",
    description: "Sports injuries, exercise science, and athletic rehabilitation professionals.",
    specialty: "Sports Medicine",
    visibility: "public",
    join_mode: "open",
    member_count: 340,
    post_count: 90,
    is_member: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c7",
    slug: "radiology-imaging",
    name: "Radiology & Imaging",
    description: "Diagnostic radiology, CT, MRI, and interventional radiology discussions.",
    specialty: "Radiology",
    visibility: "public",
    join_mode: "open",
    member_count: 470,
    post_count: 105,
    is_member: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c8",
    slug: "pediatrics-india",
    name: "Pediatrics India",
    description: "For pediatricians, neonatologists, and child health specialists.",
    specialty: "Pediatrics",
    visibility: "public",
    join_mode: "open",
    member_count: 780,
    post_count: 195,
    is_member: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ─────────────────────────────────────────────
// SAMPLE FEED POSTS
// Used on feed page when no real posts exist yet
// ─────────────────────────────────────────────

export const SAMPLE_POSTS: NetworkPost[] = [
  {
    id: "post-1",
    author_id: "sample-7",
    post_type: "research",
    content: "Excited to share our latest publication on TAVI outcomes in elderly patients with severe aortic stenosis. Our 3-year follow-up data shows significantly improved quality of life scores compared to medical management. Full paper in JACC. Link in comments. #Cardiology #Research #TAVI",
    reaction_count: 42,
    comment_count: 8,
    share_count: 15,
    visibility: "public",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    author: SAMPLE_PROFESSIONALS[6],
    user_reacted: false,
  },
  {
    id: "post-2",
    author_id: "sample-3",
    post_type: "achievement",
    content: "🏆 Thrilled to announce that our Sports Rehab team at Fortis Bangalore achieved 94% successful return-to-sport rate for ACL reconstruction patients this year! This is the result of our evidence-based progressive rehab protocol and dedicated physiotherapy team. #Physiotherapy #SportsMedicine #ACL",
    reaction_count: 118,
    comment_count: 23,
    share_count: 31,
    visibility: "public",
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    author: SAMPLE_PROFESSIONALS[2],
    user_reacted: false,
  },
  {
    id: "post-3",
    author_id: "sample-2",
    post_type: "question",
    content: "❓ Clinical question for the neurology community: What is your preferred approach for managing refractory temporal lobe epilepsy in patients who are non-surgical candidates? Looking for perspectives on newer AED combinations and VNS therapy outcomes. #Neurology #Epilepsy #ClinicalQuestion",
    reaction_count: 27,
    comment_count: 14,
    share_count: 6,
    visibility: "public",
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    author: SAMPLE_PROFESSIONALS[1],
    user_reacted: false,
  },
  {
    id: "post-4",
    author_id: "sample-8",
    post_type: "text",
    content: "Nurses are the backbone of every ICU. Today we implemented a new 12-point patient safety bundle at our unit — early mobility, daily sedation vacation, and structured family communication. In the first month we've seen a 20% reduction in ICU-acquired weakness. Sharing our protocol for peers who'd like to adopt it. 🩺 #NursingExcellence #ICU #PatientSafety",
    reaction_count: 89,
    comment_count: 17,
    share_count: 44,
    visibility: "public",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    author: SAMPLE_PROFESSIONALS[7],
    user_reacted: false,
  },
];

// ─────────────────────────────────────────────
// SPECIALTY AVATAR COLORS
// Consistent color per profession for avatars
// ─────────────────────────────────────────────

export const PROFESSION_COLORS: Record<string, string> = {
  Doctor:                  "#dbeafe",
  Nurse:                   "#dcfce7",
  Physiotherapist:         "#fef9c3",
  Pharmacist:              "#ede9fe",
  "Lab Technician":        "#fee2e2",
  Radiographer:            "#ffedd5",
  "Occupational Therapist":"#cffafe",
  "Speech Therapist":      "#fce7f3",
  Dietitian:               "#d1fae5",
  Paramedic:               "#fef3c7",
  Researcher:              "#f0fdf4",
  Student:                 "#f1f5f9",
  Educator:                "#ede9fe",
  Other:                   "#f5f5f5",
};

export function getProfessionColor(profession?: string): string {
  return PROFESSION_COLORS[profession ?? "Other"] ?? "#f5f5f5";
}

// ─────────────────────────────────────────────
// HELPER: Format relative time
// ─────────────────────────────────────────────

export function formatRelativeTime(dateStr: string): string {
  const now = Date.now();
  const date = new Date(dateStr).getTime();
  const diff = now - date;
  const seconds = Math.floor(diff / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);
  const weeks = Math.floor(days / 7);
  const months = Math.floor(days / 30);

  if (seconds < 60) return "just now";
  if (minutes < 60) return `${minutes}m`;
  if (hours < 24) return `${hours}h`;
  if (days < 7) return `${days}d`;
  if (weeks < 5) return `${weeks}w`;
  if (months < 12) return `${months}mo`;
  return `${Math.floor(months / 12)}y`;
}
