// app/api/learn/lessons/[lessonId]/transcripts/route.ts
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { getVideoTranscript, searchVideoTranscript } from "@/modules/learn/lib/video-service";
import { learnDb, ensureLearnExtensions } from "@/modules/learn/lib/learn-db";
import { generateId } from "@/modules/network/lib/network-db";

export async function GET(
  request: Request,
  { params }: { params: Promise<{ lessonId: string }> }
) {
  const { lessonId } = await params;
  if (!lessonId) {
    return Response.json({ error: "lessonId is required" }, { status: 400 });
  }

  const { searchParams } = new URL(request.url);
  const query = searchParams.get("q");
  const lang = searchParams.get("lang") || "en";

  try {
    if (query?.trim()) {
      const searchRes = await searchVideoTranscript(lessonId, query.trim());
      return Response.json(searchRes);
    }

    const transcript = await getVideoTranscript(lessonId, lang);
    return Response.json({ transcript });
  } catch (err: any) {
    console.error("GET /api/learn/lessons/[lessonId]/transcripts error:", err);
    return Response.json({ error: "Failed to fetch transcript" }, { status: 500 });
  }
}

export async function POST(
  request: Request,
  { params }: { params: Promise<{ lessonId: string }> }
) {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session?.user) {
    return Response.json({ error: "Authentication required" }, { status: 401 });
  }

  const { lessonId } = await params;
  if (!lessonId) {
    return Response.json({ error: "lessonId is required" }, { status: 400 });
  }

  try {
    await ensureLearnExtensions();
    const body = await request.json();
    const { cues, language = "en", isAutoGenerated = false } = body;

    if (!Array.isArray(cues)) {
      return Response.json({ error: "cues array is required" }, { status: 400 });
    }

    const now = new Date();
    const existing = await (learnDb as any)
      .selectFrom("video_transcripts")
      .select(["id"])
      .where("lesson_id", "=", lessonId)
      .where("language", "=", language)
      .executeTakeFirst();

    if (existing) {
      await (learnDb as any)
        .updateTable("video_transcripts")
        .set({
          cues: JSON.stringify(cues),
          is_auto_generated: Boolean(isAutoGenerated),
          updated_at: now,
        })
        .where("id", "=", existing.id)
        .execute();
    } else {
      await (learnDb as any)
        .insertInto("video_transcripts")
        .values({
          id: generateId(),
          lesson_id: lessonId,
          language,
          cues: JSON.stringify(cues),
          is_auto_generated: Boolean(isAutoGenerated),
          is_verified: true,
          created_at: now,
          updated_at: now,
        })
        .execute();
    }

    const updated = await getVideoTranscript(lessonId, language);
    return Response.json({ transcript: updated });
  } catch (err: any) {
    console.error("POST /api/learn/lessons/[lessonId]/transcripts error:", err);
    return Response.json({ error: "Failed to save transcript" }, { status: 500 });
  }
}
